spring:
  kafka:
    security:
      protocol: "SSL"
    bootstrap-servers: instance-1:9093
    ssl:
      trust-store-location: /data/certs/truststore.jks
      trust-store-password: password
      key-store-location:  /data/certs/keystore.jks
      key-store-password: password
    consumer:
      group-id: group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
